; Syndro — Inno Setup installer script (per-user install, no admin required).
;
; Compiled from CI (see .github/workflows/release.yml, "Compile Windows installer"):
;   ISCC.exe /DMyAppVersion=1.0.1 "/DReleaseDir=C:\...\syndro-windows" "/OC:\...\dist" installer\SyndroInstaller.iss
;
; {source} is the directory containing this file, so the app icon path below
; resolves to windows\runner\resources\app_icon.ico (regenerated by
; flutter create + flutter_launcher_icons in CI before this step runs).

#ifndef MyAppVersion
  #define MyAppVersion "0.0.0"
#endif

#ifndef ReleaseDir
  #error "Define /DReleaseDir=<path to the built release folder>"
#endif

; The app icon is generated by `flutter create --platforms=windows` +
; `flutter_launcher_icons` in CI. Fall back to no setup icon if it is absent
; (e.g. compiling against a local build that never ran icon generation).
#ifndef MyAppIcon
  #if FileExists("..\windows\runner\resources\app_icon.ico")
    #define MyAppIcon "..\windows\runner\resources\app_icon.ico"
  #else
    #define MyAppIcon ""
  #endif
#endif

#define MyAppName "Syndro"
#define MyAppPublisher "Syndro"
#define MyAppExeName "Syndro.exe"
#define MyAppURL "https://github.com/FakeAbid11/Syndro"

[Setup]
; Fixed AppId so future versions upgrade over the same installation.
AppId={{9F8D2B4A-7C3E-4A6B-9D1F-5E8C2A7B4D3F}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
; The in-app updater exits Syndro before running the installer, but force-close
; any lingering instance so file replacement can never fail on a locked exe.
CloseApplications=yes
CloseApplicationsFilter={#MyAppExeName}
OutputBaseFilename=Syndro-Setup-{#MyAppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
#if MyAppIcon != ""
SetupIconFile={#MyAppIcon}
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#ReleaseDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; `nowait postinstall` without `skipifsilent`: the interactive wizard still
; shows the "Launch Syndro" checkbox, and a silent install (in-app updater:
; /VERYSILENT) automatically relaunches the updated app.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall